mdoc should not use TypeMap for parameter and return elements
mono/api-doc-tools pull request #558
Opened 2021-05-18 08:27 UTC by michaeljin89757

2021-05-18 21:31 UTC, joelmartinez requested changes
This is great, but the same type of change also needs to be added for parameter types. Look at the `MakeParameters` function

2021-05-19 14:20 UTC, joelmartinez requested changes
Thank you, yes this change looks good as well, and I appreciate that you added the default parameter so that any other callers who might be using `GetDocParameterType` will still get the original behavior.

In my haste yesterday, I asked for only this one change ... but that was partially because I was reacting to an urgent need to unblock @TianqiZhang. In the meantime, @anmeng10101 has created a preview release that includes this change so that has unblocked. So I would like to request one other change.

It's interesting that this hasn't triggered any changes in our expected integration test files ... which means that we must not have any typemap integration tests. I'd like to request that you add an integration test, along with expected XML files, that uses a typemap file, and we see the mapped type in the signature, but the original type in the return and parameter elements.

This way we can codify the behavior in our integration test suite, and better guard against regressions in the future. Thanks!

2021-05-27 09:06 UTC, michaeljin89757 commented
![Parameter](https://user-images.githubusercontent.com/54333536/119798366-a940ac00-bf0d-11eb-987e-095df50afb95.png)
![ReturnValue](https://user-images.githubusercontent.com/54333536/119798387-ab0a6f80-bf0d-11eb-8f58-22bb6e983250.png)
 Here are two pictures of before and after change.
 On the left side is the result after the change. On the right side is the result from a mdoc local run using main branch.

2021-05-28 15:33 UTC, joelmartinez requested changes

2021-05-28 15:33 UTC, joelmartinez commented on mdoc/Makefile
> +	cp Test/TypeMap.xml Test/test-type-projection/
You should give `TypeMap.xml` a different name in the `Test` directory ... something that makes it clearer which test it's related to. You can rename it after you copy with the `mv` command.

2021-05-28 15:33 UTC, joelmartinez commented on mdoc/Test/en.expected-fsharp-wsl/Delegates+Delegate10.xml
> +  <TypeSignature Language="C#" Value="public delegate char Delegates.Delegate10(int unnamedParam1, int unnamedParam2);" />
It's really strange that we're getting all these changes only now in this PR, when the unnamed parameter change happened all the way back in february with #535 🤔

2021-05-28 15:33 UTC, joelmartinez commented on mdoc/Test/en.expected-type-projection/Mono.DocTest/IList.xml
> +        <Parameter Name="A" Type="System.Collections.IList" />
I would have expected this parameter type to be `Mono.DocTest.IVector` as well just like in the return value ... this result here shows that it's still using the type map

2021-06-04 14:07 UTC, joelmartinez approved these changes
Thanks for the great work on adding the integration testing ... really helped capture some things that otherwise would have gone unnoticed. This LGTM /cc @anmeng10101

2021-06-04 14:11 UTC, merged